### ISSUE TITLE
Use signhash-contracts NPM package

### ISSUE THREAD

**Issue by jksf** [SignHash/signhash-webapp#28]
I'd like to migrate from using contracts as git dependency to NPM package recently published and awaiting approval in https://github.com/SignHash/signhash-contracts/pull/33

The changes may affect any parts related to `testrpc` and compiled contracts.
@biern Is there something I have to watch out for? Some unobvious dependencies or assumptions?

**Comment by biern** [comment]
So the webapp depends on the contracts in the following way:
- it uses npm explore to run migration script
- it assumes that the built contracts json files are located in `node_modules/signhash-contracts/build/contracts`

Since webapp has started using testrpc API extensively for the build process I've made an explicit dev dependency webapp -> ethereumjs-testrpc , so contracts testrpc version should be of no concern to the webapp. Actually I believe there's even no need to share the seed script with the app in it's current state.
